// Comprehensive currency database
const CURRENCIES = {
  USD: { name: "United States Dollar", symbol: "$", flag: "🇺🇸" },
  EUR: { name: "Euro", symbol: "€", flag: "🇪🇺" },
  GBP: { name: "British Pound Sterling", symbol: "£", flag: "🇬🇧" },
  INR: { name: "Indian Rupee", symbol: "₹", flag: "🇮🇳" },
  JPY: { name: "Japanese Yen", symbol: "¥", flag: "🇯🇵" },
  AUD: { name: "Australian Dollar", symbol: "A$", flag: "🇦🇺" },
  CAD: { name: "Canadian Dollar", symbol: "C$", flag: "🇨🇦" },
  CHF: { name: "Swiss Franc", symbol: "CHF", flag: "🇨🇭" },
  CNY: { name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳" },
  SEK: { name: "Swedish Krona", symbol: "kr", flag: "🇸🇪" },
  NZD: { name: "New Zealand Dollar", symbol: "NZ$", flag: "🇳🇿" },
  MXN: { name: "Mexican Peso", symbol: "$", flag: "🇲🇽" },
  SGD: { name: "Singapore Dollar", symbol: "S$", flag: "🇸🇬" },
  HKD: { name: "Hong Kong Dollar", symbol: "HK$", flag: "🇭🇰" },
  NOK: { name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴" },
  KRW: { name: "South Korean Won", symbol: "₩", flag: "🇰🇷" },
  TRY: { name: "Turkish Lira", symbol: "₺", flag: "🇹🇷" },
  RUB: { name: "Russian Ruble", symbol: "₽", flag: "🇷🇺" },
  BRL: { name: "Brazilian Real", symbol: "R$", flag: "🇧🇷" },
  ZAR: { name: "South African Rand", symbol: "R", flag: "🇿🇦" },
  DKK: { name: "Danish Krone", symbol: "kr", flag: "🇩🇰" },
  PLN: { name: "Polish Zloty", symbol: "zł", flag: "🇵🇱" },
  THB: { name: "Thai Baht", symbol: "฿", flag: "🇹🇭" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩" },
  HUF: { name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺" },
  CZK: { name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿" },
  ILS: { name: "Israeli New Shekel", symbol: "₪", flag: "🇮🇱" },
  CLP: { name: "Chilean Peso", symbol: "$", flag: "🇨🇱" },
  PHP: { name: "Philippine Peso", symbol: "₱", flag: "🇵🇭" },
  AED: { name: "UAE Dirham", symbol: "د.إ", flag: "🇦🇪" },
  COP: { name: "Colombian Peso", symbol: "$", flag: "🇨🇴" },
  SAR: { name: "Saudi Riyal", symbol: "﷼", flag: "🇸🇦" },
  RON: { name: "Romanian Leu", symbol: "lei", flag: "🇷🇴" },
  VND: { name: "Vietnamese Dong", symbol: "₫", flag: "🇻🇳" },
  ARS: { name: "Argentine Peso", symbol: "$", flag: "🇦🇷" },
  IQD: { name: "Iraqi Dinar", symbol: "ع.د", flag: "🇮🇶" },
  TWD: { name: "New Taiwan Dollar", symbol: "NT$", flag: "🇹🇼" },
  QAR: { name: "Qatari Riyal", symbol: "﷼", flag: "🇶🇦" },
  PKR: { name: "Pakistani Rupee", symbol: "₨", flag: "🇵🇰" },
  KWD: { name: "Kuwaiti Dinar", symbol: "د.ك", flag: "🇰🇼" },
  NGN: { name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬" },
  EGP: { name: "Egyptian Pound", symbol: "£", flag: "🇪🇬" },
  BDT: { name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩" },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴", flag: "🇺🇦" },
  PEN: { name: "Peruvian Sol", symbol: "S/", flag: "🇵🇪" },
  KES: { name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪" },
  OMR: { name: "Omani Rial", symbol: "﷼", flag: "🇴🇲" },
  BGN: { name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬" },
  VEF: { name: "Venezuelan Bolívar", symbol: "Bs", flag: "🇻🇪" },
  MAD: { name: "Moroccan Dirham", symbol: "د.م.", flag: "🇲🇦" },
  HRK: { name: "Croatian Kuna", symbol: "kn", flag: "🇭🇷" },
  LKR: { name: "Sri Lankan Rupee", symbol: "₨", flag: "🇱🇰" },
  UYU: { name: "Uruguayan Peso", symbol: "$U", flag: "🇺🇾" },
  GHS: { name: "Ghanaian Cedi", symbol: "₵", flag: "🇬🇭" },
  DZD: { name: "Algerian Dinar", symbol: "د.ج", flag: "🇩🇿" },
  JOD: { name: "Jordanian Dinar", symbol: "د.ا", flag: "🇯🇴" },
  BHD: { name: "Bahraini Dinar", symbol: ".د.ب", flag: "🇧🇭" },
  TND: { name: "Tunisian Dinar", symbol: "د.ت", flag: "🇹🇳" },
  ISK: { name: "Icelandic Króna", symbol: "kr", flag: "🇮🇸" },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹" },
  DOP: { name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴" },
  CRC: { name: "Costa Rican Colón", symbol: "₡", flag: "🇨🇷" },
  ETB: { name: "Ethiopian Birr", symbol: "Br", flag: "🇪🇹" },
  LBP: { name: "Lebanese Pound", symbol: "£", flag: "🇱🇧" },
  MMK: { name: "Myanmar Kyat", symbol: "K", flag: "🇲🇲" },
  AZN: { name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿" },
  UZS: { name: "Uzbekistani Som", symbol: "лв", flag: "🇺🇿" },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs.", flag: "🇧🇴" },
  AFN: { name: "Afghan Afghani", symbol: "؋", flag: "🇦🇫" },
  ALL: { name: "Albanian Lek", symbol: "L", flag: "🇦🇱" },
  AMD: { name: "Armenian Dram", symbol: "֏", flag: "🇦🇲" },
  AOA: { name: "Angolan Kwanza", symbol: "Kz", flag: "🇦🇴" },
  AWG: { name: "Aruban Florin", symbol: "ƒ", flag: "🇦🇼" },
  BAM: { name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", flag: "🇧🇦" },
  BBD: { name: "Barbadian Dollar", symbol: "$", flag: "🇧🇧" },
  BND: { name: "Brunei Dollar", symbol: "$", flag: "🇧🇳" },
  BSD: { name: "Bahamian Dollar", symbol: "$", flag: "🇧🇸" },
  BWP: { name: "Botswanan Pula", symbol: "P", flag: "🇧🇼" },
  BYN: { name: "Belarusian Ruble", symbol: "Br", flag: "🇧🇾" },
  BZD: { name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿" },
  CDF: { name: "Congolese Franc", symbol: "FC", flag: "🇨🇩" },
  CUP: { name: "Cuban Peso", symbol: "₱", flag: "🇨🇺" },
  CVE: { name: "Cape Verdean Escudo", symbol: "$", flag: "🇨🇻" },
  DJF: { name: "Djiboutian Franc", symbol: "Fdj", flag: "🇩🇯" },
  ERN: { name: "Eritrean Nakfa", symbol: "Nfk", flag: "🇪🇷" },
  FJD: { name: "Fijian Dollar", symbol: "$", flag: "🇫🇯" },
  GEL: { name: "Georgian Lari", symbol: "₾", flag: "🇬🇪" },
  GIP: { name: "Gibraltar Pound", symbol: "£", flag: "🇬🇮" },
  GMD: { name: "Gambian Dalasi", symbol: "D", flag: "🇬🇲" },
  GNF: { name: "Guinean Franc", symbol: "FG", flag: "🇬🇳" },
  GYD: { name: "Guyanaese Dollar", symbol: "$", flag: "🇬🇾" },
  HNL: { name: "Honduran Lempira", symbol: "L", flag: "🇭🇳" },
  HTG: { name: "Haitian Gourde", symbol: "G", flag: "🇭🇹" },
  JMD: { name: "Jamaican Dollar", symbol: "J$", flag: "🇯🇲" },
  KGS: { name: "Kyrgystani Som", symbol: "лв", flag: "🇰🇬" },
  KHR: { name: "Cambodian Riel", symbol: "៛", flag: "🇰🇭" },
  KMF: { name: "Comorian Franc", symbol: "CF", flag: "🇰🇲" },
  KYD: { name: "Cayman Islands Dollar", symbol: "$", flag: "🇰🇾" },
  KZT: { name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿" },
  LAK: { name: "Laotian Kip", symbol: "₭", flag: "🇱🇦" },
  LRD: { name: "Liberian Dollar", symbol: "$", flag: "🇱🇷" },
  LSL: { name: "Lesotho Loti", symbol: "L", flag: "🇱🇸" },
  LYD: { name: "Libyan Dinar", symbol: "ل.د", flag: "🇱🇾" },
  MDL: { name: "Moldovan Leu", symbol: "L", flag: "🇲🇩" },
  MGA: { name: "Malagasy Ariary", symbol: "Ar", flag: "🇲🇬" },
  MKD: { name: "Macedonian Denar", symbol: "ден", flag: "🇲🇰" },
  MNT: { name: "Mongolian Tugrik", symbol: "₮", flag: "🇲🇳" },
  MOP: { name: "Macanese Pataca", symbol: "MOP$", flag: "🇲🇴" },
  MRU: { name: "Mauritanian Ouguiya", symbol: "UM", flag: "🇲🇷" },
  MUR: { name: "Mauritian Rupee", symbol: "₨", flag: "🇲🇺" },
  MVR: { name: "Maldivian Rufiyaa", symbol: "Rf", flag: "🇲🇻" },
  MWK: { name: "Malawian Kwacha", symbol: "MK", flag: "🇲🇼" },
  MZN: { name: "Mozambican Metical", symbol: "MT", flag: "🇲🇿" },
  NAD: { name: "Namibian Dollar", symbol: "$", flag: "🇳🇦" },
  NIO: { name: "Nicaraguan Córdoba", symbol: "C$", flag: "🇳🇮" },
  NPR: { name: "Nepalese Rupee", symbol: "₨", flag: "🇳🇵" },
  PAB: { name: "Panamanian Balboa", symbol: "B/.", flag: "🇵🇦" },
  PGK: { name: "Papua New Guinean Kina", symbol: "K", flag: "🇵🇬" },
  PYG: { name: "Paraguayan Guarani", symbol: "₲", flag: "🇵🇾" },
  RSD: { name: "Serbian Dinar", symbol: "Дин.", flag: "🇷🇸" },
  RWF: { name: "Rwandan Franc", symbol: "FRw", flag: "🇷🇼" },
  SBD: { name: "Solomon Islands Dollar", symbol: "$", flag: "🇸🇧" },
  SCR: { name: "Seychellois Rupee", symbol: "₨", flag: "🇸🇨" },
  SDG: { name: "Sudanese Pound", symbol: "ج.س.", flag: "🇸🇩" },
  SLL: { name: "Sierra Leonean Leone", symbol: "Le", flag: "🇸🇱" },
  SOS: { name: "Somali Shilling", symbol: "S", flag: "🇸🇴" },
  SRD: { name: "Surinamese Dollar", symbol: "$", flag: "🇸🇷" },
  STN: { name: "São Tomé and Príncipe Dobra", symbol: "Db", flag: "🇸🇹" },
  SYP: { name: "Syrian Pound", symbol: "£", flag: "🇸🇾" },
  SZL: { name: "Swazi Lilangeni", symbol: "L", flag: "🇸🇿" },
  TJS: { name: "Tajikistani Somoni", symbol: "SM", flag: "🇹🇯" },
  TMT: { name: "Turkmenistani Manat", symbol: "T", flag: "🇹🇲" },
  TOP: { name: "Tongan Paʻanga", symbol: "T$", flag: "🇹🇴" },
  TTD: { name: "Trinidad and Tobago Dollar", symbol: "TT$", flag: "🇹🇹" },
  TZS: { name: "Tanzanian Shilling", symbol: "TSh", flag: "🇹🇿" },
  UGX: { name: "Ugandan Shilling", symbol: "USh", flag: "🇺🇬" },
  XAF: { name: "Central African CFA Franc", symbol: "FCFA", flag: "🌍" },
  XCD: { name: "East Caribbean Dollar", symbol: "$", flag: "🌎" },
  XOF: { name: "West African CFA Franc", symbol: "CFA", flag: "🌍" },
  XPF: { name: "CFP Franc", symbol: "₣", flag: "🌏" },
  YER: { name: "Yemeni Rial", symbol: "﷼", flag: "🇾🇪" },
  ZMW: { name: "Zambian Kwacha", symbol: "ZK", flag: "🇿🇲" },
  ZWL: { name: "Zimbabwean Dollar", symbol: "Z$", flag: "🇿🇼" },
  
  // Cryptocurrencies
  BTC: { name: "Bitcoin", symbol: "₿", flag: "🪙" },
  ETH: { name: "Ethereum", symbol: "Ξ", flag: "🪙" },
  BNB: { name: "Binance Coin", symbol: "BNB", flag: "🪙" },
  SOL: { name: "Solana", symbol: "SOL", flag: "🪙" },
  XRP: { name: "Ripple", symbol: "XRP", flag: "🪙" },
  ADA: { name: "Cardano", symbol: "ADA", flag: "🪙" },
  DOGE: { name: "Dogecoin", symbol: "Ð", flag: "🪙" },
  MATIC: { name: "Polygon", symbol: "MATIC", flag: "🪙" },
  DOT: { name: "Polkadot", symbol: "DOT", flag: "🪙" },
  AVAX: { name: "Avalanche", symbol: "AVAX", flag: "🪙" }
};

// Currency symbol to code mapping (for detection)
const CURRENCY_SYMBOLS = {
  "$": ["USD", "AUD", "CAD", "MXN", "SGD", "HKD", "NZD"],
  "€": ["EUR"],
  "£": ["GBP"],
  "₹": ["INR"],
  "¥": ["JPY", "CNY"],
  "₽": ["RUB"],
  "₩": ["KRW"],
  "₺": ["TRY"],
  "R$": ["BRL"],
  "₪": ["ILS"],
  "₱": ["PHP"],
  "₫": ["VND"],
  "₦": ["NGN"],
  "₨": ["PKR", "NPR", "LKR"],
  "฿": ["THB"],
  "₡": ["CRC"],
  "₴": ["UAH"],
  "₸": ["KZT"],
  "₼": ["AZN"],
  "₾": ["GEL"],
  "₿": ["BTC"],
  "Ξ": ["ETH"]
};

// Default pinned currencies
const DEFAULT_PINNED = ["USD", "EUR", "GBP", "INR", "JPY", "AUD"];

// API configurations
const API_CONFIGS = [
  {
    name: "ExchangeRate-API",
    url: (base) => `https://open.er-api.com/v6/latest/${base}`,
    parse: (data) => data.result === "success" ? data.rates : null
  },
  {
    name: "Frankfurter",
    url: (base) => `https://api.frankfurter.app/latest?from=${base}`,
    parse: (data) => data.rates ? { ...data.rates, [data.base]: 1 } : null
  },
  {
    name: "ExchangeRate.host",
    url: (base) => `https://api.exchangerate.host/latest?base=${base}`,
    parse: (data) => data.success ? data.rates : null
  }
];
